#############################
#         DASHBOARD         #
#############################
cdc_core_dashboardpage:
    path: /
    defaults:
        _controller: CDCCoreBundle:Dashboard:overview
        format: html
    requirements:
        format: html|xml

#############################
#         TRANSFERT         #
#############################
cdc_core_transfertpage:
    path: /transfert/overview
    defaults:
        _controller: CDCCoreBundle:Transfert:overview
        format: html
    requirements:
        format: html|xml
    options:
        expose: true

cdc_core_addtransfert:
    path: /transfert/addtransfert
    defaults:
        _controller: CDCCoreBundle:Transfert:addTransfert
        format: html
    requirements:
        format: html|xml
    options:
        expose: true

cdc_core_deletetransfert:
    path: /transfert/deletetransfert/{id}
    defaults:
        _controller: CDCCoreBundle:Transfert:deleteTransfert
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_edittransfert:
    path: /transfert/edittransfert/{id}
    defaults:
        _controller: CDCCoreBundle:Transfert:editTransfert
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_retrievetransfert:
    path: /transfert/retrievetransfert/{id}
    defaults:
        _controller: CDCCoreBundle:Transfert:retrieveTransfert
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

#############################
#         PROFILE           #
#############################
cdc_core_profilepage:
    path: /profile/overview
    defaults:
        _controller: CDCCoreBundle:Profile:overview
        format: html
    requirements:
        format: html|xml
    options:
        expose: true

#############################
#         COMPTE            #
#############################
cdc_core_comptepage:
    path: /comptes/overview
    defaults:
        _controller: CDCCoreBundle:Compte:overview
        format: html
    requirements:
        format: html|xml

cdc_core_addcompte:
    path: /compte/addcompte
    defaults:
        _controller: CDCCoreBundle:Compte:addCompte
        format: html
    requirements:
        format: html|xml
    options:
        expose: true

cdc_core_deletecompte:
    path: /compte/deletecompte/{id}
    defaults:
        _controller: CDCCoreBundle:Compte:deleteCompte
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_editcompte:
    path: /compte/editcompte/{id}
    defaults:
        _controller: CDCCoreBundle:Compte:editCompte
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

#############################
#         CATEGORIE         #
#############################
cdc_core_categoriepage:
    path: /categorie/overview
    defaults:
        _controller: CDCCoreBundle:Categorie:Overview
        format: html
    requirements:
        format: html|xml
    options:
        expose: true

cdc_core_addcategorie:
    path: /categorie/addcategorie/{id}
    defaults:
        _controller: CDCCoreBundle:Categorie:addCategorie
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_deletecategorie:
    path: /categorie/deletecategorie/{id}
    defaults:
        _controller: CDCCoreBundle:Categorie:deleteCategorie
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

#############################
#         BUDGET            #
#############################
cdc_core_budgetpage:
    path: /budget/overview
    defaults:
        _controller: CDCCoreBundle:Budget:overview
        format: html
    requirements:
        format: html|xml

cdc_core_addbudgetmodele:
    path: /budget/addbudgetmodele/id
    defaults:
        _controller: CDCCoreBundle:Budget:addBudgetModele
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_editbudgetmodele:
    path: /budget/editbudgetmodele/id
    defaults:
        _controller: CDCCoreBundle:Budget:editBudgetModele
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true

cdc_core_deletebudgetmodele:
    path: /budget/deletebudgetmodele/id
    defaults:
        _controller: CDCCoreBundle:Budget:deleteBudgetModele
        format: html
    requirements:
        id: \d+
        format: html|xml
    options:
        expose: true